CREATE TABLE [Album] (
	ID integer NOT NULL,
	CoverImage integer NOT NULL,
	Title text NOT NULL,
	Description integer NOT NULL,
	PublicationDate datetime NOT NULL,
	DBCreationDate datetime NOT NULL,
  CONSTRAINT [PK_ALBUM] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Song] (
	ID integer NOT NULL UNIQUE,
	Artist integer NOT NULL,
	Album integer,
	Image integer,
	Genre integer NOT NULL,
	Score integer NOT NULL DEFAULT '0',
	Title text NOT NULL,
	CreationDate datetime NOT NULL,
	FilePath text,
	Length timestamp NOT NULL,
	Bitrate integer NOT NULL,
	DBCreationDate datetime NOT NULL,
	PlayTimes integer NOT NULL DEFAULT '0',
  CONSTRAINT [PK_SONG] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Playlist] (
	ID integer NOT NULL,
	Name text NOT NULL,
	DBCreationDate datetime NOT NULL,
	Description datetime NOT NULL,
  CONSTRAINT [PK_PLAYLIST] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Artist] (
	ID integer NOT NULL,
	Band integer,
	Photo integer NOT NULL,
	Name text NOT NULL,
	Surname text NOT NULL,
	Pseudonym text NOT NULL,
	Birthdate datetime NOT NULL,
	Description text NOT NULL,
  CONSTRAINT [PK_ARTIST] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [SongAlbum] (
	AlbumID integer NOT NULL,
	SongID integer NOT NULL,
	TrackNumber integer NOT NULL,
  CONSTRAINT [PK_SONGALBUM] PRIMARY KEY CLUSTERED
  (
  [AlbumID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [SongArtist] (
	ArtistID integer NOT NULL,
	SongID integer NOT NULL,
  CONSTRAINT [PK_SONGARTIST] PRIMARY KEY CLUSTERED
  (
  [ArtistID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Image] (
	ID integer NOT NULL,
	FilePath text NOT NULL,
  CONSTRAINT [PK_IMAGE] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [SongPlaylist] (
	PlaylistID integer NOT NULL,
	SongID integer NOT NULL,
	Order integer NOT NULL,
  CONSTRAINT [PK_SONGPLAYLIST] PRIMARY KEY CLUSTERED
  (
  [PlaylistID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Band] (
	ID integer NOT NULL,
	Name text NOT NULL,
	CreationDate datetime NOT NULL,
	EndDate datetime,
	Description text NOT NULL,
  CONSTRAINT [PK_BAND] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Genre] (
	ID integer NOT NULL,
	Name text NOT NULL,
	Description text NOT NULL,
  CONSTRAINT [PK_GENRE] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [PlayQueue] (
	ID integer NOT NULL,
	Song integer NOT NULL,
  CONSTRAINT [PK_PLAYQUEUE] PRIMARY KEY CLUSTERED
  (
  [ID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
ALTER TABLE [Album] WITH CHECK ADD CONSTRAINT [Album_fk0] FOREIGN KEY ([CoverImage]) REFERENCES [Image]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Album] CHECK CONSTRAINT [Album_fk0]
GO

ALTER TABLE [Song] WITH CHECK ADD CONSTRAINT [Song_fk0] FOREIGN KEY ([ID]) REFERENCES [SongPlaylist]([SongID])
ON UPDATE CASCADE
GO
ALTER TABLE [Song] CHECK CONSTRAINT [Song_fk0]
GO
ALTER TABLE [Song] WITH CHECK ADD CONSTRAINT [Song_fk1] FOREIGN KEY ([Artist]) REFERENCES [SongArtist]([SongID])
ON UPDATE CASCADE
GO
ALTER TABLE [Song] CHECK CONSTRAINT [Song_fk1]
GO
ALTER TABLE [Song] WITH CHECK ADD CONSTRAINT [Song_fk2] FOREIGN KEY ([Album]) REFERENCES [SongAlbum]([SongID])
ON UPDATE CASCADE
GO
ALTER TABLE [Song] CHECK CONSTRAINT [Song_fk2]
GO
ALTER TABLE [Song] WITH CHECK ADD CONSTRAINT [Song_fk3] FOREIGN KEY ([Image]) REFERENCES [Image]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Song] CHECK CONSTRAINT [Song_fk3]
GO
ALTER TABLE [Song] WITH CHECK ADD CONSTRAINT [Song_fk4] FOREIGN KEY ([Genre]) REFERENCES [Genre]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Song] CHECK CONSTRAINT [Song_fk4]
GO


ALTER TABLE [Artist] WITH CHECK ADD CONSTRAINT [Artist_fk0] FOREIGN KEY ([Band]) REFERENCES [Band]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Artist] CHECK CONSTRAINT [Artist_fk0]
GO
ALTER TABLE [Artist] WITH CHECK ADD CONSTRAINT [Artist_fk1] FOREIGN KEY ([Photo]) REFERENCES [Image]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [Artist] CHECK CONSTRAINT [Artist_fk1]
GO

ALTER TABLE [SongAlbum] WITH CHECK ADD CONSTRAINT [SongAlbum_fk0] FOREIGN KEY ([AlbumID]) REFERENCES [Album]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [SongAlbum] CHECK CONSTRAINT [SongAlbum_fk0]
GO

ALTER TABLE [SongArtist] WITH CHECK ADD CONSTRAINT [SongArtist_fk0] FOREIGN KEY ([ArtistID]) REFERENCES [Artist]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [SongArtist] CHECK CONSTRAINT [SongArtist_fk0]
GO


ALTER TABLE [SongPlaylist] WITH CHECK ADD CONSTRAINT [SongPlaylist_fk0] FOREIGN KEY ([PlaylistID]) REFERENCES [Playlist]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [SongPlaylist] CHECK CONSTRAINT [SongPlaylist_fk0]
GO



ALTER TABLE [PlayQueue] WITH CHECK ADD CONSTRAINT [PlayQueue_fk0] FOREIGN KEY ([Song]) REFERENCES [Song]([ID])
ON UPDATE CASCADE
GO
ALTER TABLE [PlayQueue] CHECK CONSTRAINT [PlayQueue_fk0]
GO

